using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.EntityFrameworkCore;
using OrderProcessing.Persistence;
using OrderProcessing.Persistence.Entities;

namespace OrderProcessing.Api.Orders;

public static class OrderEndpoints
{
    public static RouteGroupBuilder MapOrderEndpoints(this IEndpointRouteBuilder routes)
    {
        ArgumentNullException.ThrowIfNull(routes);

        var group = routes.MapGroup("/api/orders").WithTags("Orders");

        group.MapPost("/", PlaceOrderAsync)
            .WithName("PlaceOrder")
            .WithSummary("Accepts an order for asynchronous processing.");

        group.MapGet("/{id:guid}", GetOrderAsync)
            .WithName("GetOrder")
            .WithSummary("Reports where an order has got to.");

        return group;
    }

    /// <summary>
    /// Accepts the order and answers immediately.
    ///
    /// The response is 202, not 201, and the difference is the whole point of this project. 201
    /// would promise that the thing the caller asked for now exists and is complete. It does not:
    /// the order has been recorded and a receipt will be generated by another process, at some
    /// point, possibly after several retries. 202 says exactly that, and the Location header says
    /// where to look to find out.
    /// </summary>
    private static async Task<Results<Accepted<OrderAcceptedResponse>, ValidationProblem>> PlaceOrderAsync(
        PlaceOrderRequest request,
        OrderProcessingDbContext database,
        TimeProvider clock,
        CancellationToken cancellationToken)
    {
        if (!OrderRequestValidator.IsValid(request, out var errors))
        {
            return TypedResults.ValidationProblem(errors);
        }

        var order = new Order
        {
            // Chosen here, not by the database. The same id has to appear in this response and - from
            // Phase 07 - in an outbox row written in the same transaction, so the application has to
            // know it before anything is saved.
            Id = Guid.CreateVersion7(),
            CustomerEmail = request.CustomerEmail,
            Status = OrderStatus.Accepted,
            PlacedAt = clock.GetUtcNow(),

            // Computed here rather than accepted from the caller. A client that can state its own
            // total can state a total of zero.
            Total = request.Lines.Sum(l => l.Quantity * l.UnitPrice),
        };

        foreach (var line in request.Lines)
        {
            order.Lines.Add(new OrderLine
            {
                OrderId = order.Id,
                Sku = line.Sku,
                Description = line.Description,
                Quantity = line.Quantity,
                UnitPrice = line.UnitPrice,
            });
        }

        database.Orders.Add(order);
        await database.SaveChangesAsync(cancellationToken).ConfigureAwait(false);

        return TypedResults.Accepted(
            $"/api/orders/{order.Id}",
            new OrderAcceptedResponse(order.Id, order.Status.ToString()));
    }

    private static async Task<Results<Ok<OrderResponse>, ProblemHttpResult>> GetOrderAsync(
        Guid id,
        OrderProcessingDbContext database,
        CancellationToken cancellationToken)
    {
        var order = await database.Orders
            .Include(o => o.Lines)
            // Nothing here is written to, and a read that cannot be written back does not need
            // change tracking. It is the cheapest correctness-neutral thing available.
            .AsNoTracking()
            .FirstOrDefaultAsync(o => o.Id == id, cancellationToken)
            .ConfigureAwait(false);

        return order is null
            ? TypedResults.Problem(
                title: "Order not found",
                detail: $"No order with id {id}.",
                statusCode: StatusCodes.Status404NotFound)
            : TypedResults.Ok(OrderResponse.From(order));
    }

}
